#!/bin/bash

# Exit script on failure
set -e

# Install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# Install CLI applications
# figlet, lolcat for printing date on startup
# gawk for tmux-fingers plugin
# neovim, "vim" is aliased to it
brew install tmux z youtube-dl vim figlet lolcat curl hub gawk neovim

## GUI Applications

# Enable homebrew cask
brew tap caskroom/cask
# Install all these apps
brew cask install flux spectacle spotify spotifree sublime-text
# Install Mac App Store CLI
brew install mas
# Install yregex
mas lucky yregex


# Install nvm. TODO: Can I just add a git submodule for this? It's already in my .bash_profile
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
# Install node
nvm install node
# Use it by default instead of system node
nvm alias default node


# Set delay until repeat speed to system minimum
defaults write -g InitialKeyRepeat -int 15
# Set key Repeat to system minimum
defaults write -g KeyRepeat -int 2
