#!/bin/bash

ffmpeg -i "$1" -i "$2" -filter_complex "[0:a]showwaves=s=1280x720:mode=line:colors=White,colorkey=0x000000:0.01:0.1,format=yuva420p[v];[1:v]scale=1280:720[bg];[bg][v]overlay[outv]" -map "[outv]" -map 0:a -c:v libx264 -pix_fmt yuv420p -b:a 360k -r:a 44100 "$1.mp4"
