#!/bin/bash

ffmpeg -i $1 -preset slow -codec:a libfdk_aac -b:a 128k -codec:v libx264 -pix_fmt yuv420p -b:v 4500k -minrate 4500k -maxrate 9000k -bufsize 9000k -vf scale=-1:1080 -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" $2
